### ISSUE TITLE
Suggestion: Rarities and rarity weight as parameters

### ISSUE THREAD

**Issue by mjs92** [Oheers/EvenMoreFish#101]
Could you add rarities and rarity weight as parameters for specific competition?

Setting up some competition to have higher probability of legendaries is fun, same for another competition with special type fish.
Problem is, I don't have option to do it in single config file, I have to make couple of them and switch them depending on what I want to do.

**Comment by Oheers** [comment]
I'm in the process of adding baits, I could have them trigger for everyone when a competition starts, this has been added to the todo list, thank you for your suggestion :)

**Comment by Oheers** [comment]
This has now been released on the SpigotMC plugin page.
