### ISSUE TITLE
Ability to add sound when a competition starts / ends

### ISSUE THREAD

**Issue by SomeKoder** [Oheers/EvenMoreFish#102]
First off, great plugin! No issues so far.

I think it would be really nice to be able to have a sound accompanied by the boss bar and chat message.

Would it be possible to add this functionality?

**Comment by Oheers** [comment]
It would definitely be possible, I'll aim to have it in the upcoming 1.5 update with baits, which could be around a month from now.

**Comment by SomeKoder** [comment]
Awesome! Thank you! Looking very much forward to it 😃

**Comment by Oheers** [comment]
Hey there, this is included in the latest dev build of the plugin, which can be found on [the jenkins build server](https://ci.codemc.io/job/Oheers/job/EvenMoreFish/).

Add `start-sound` to your general section or individual competition section in `competitions.yml` and use a sound from [the spigot javadocs for "Sound"](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html).
