### ISSUE TITLE
sell all Inventory bug

### ISSUE THREAD

**Issue by SrT3ddy** [Oheers/EvenMoreFish#106]
![Screenshot_1](https://user-images.githubusercontent.com/82233732/152706595-2485e733-3036-48df-abcb-534c6d0ab276.png)
![Screenshot_2](https://user-images.githubusercontent.com/82233732/152706602-e503036e-a887-43fe-9784-5490e9001ae9.png)
![Screenshot_3](https://user-images.githubusercontent.com/82233732/152706604-133da4aa-06b2-4acf-9f5b-8a8e14eb4ad3.png)

Inventory sales do not count if any fish is on your sales menu and ends up excluding what is inside and only what is in the inventory is sold.

**Comment by Oheers** [comment]
Hi there, apologies for the late response, this is fixed in the latest build and will be included in the next spigot release. Thank you very much for reporting it though :) If you'd like the build earlier feel free to message me on the discord server or compile the code yourself.

- Oheers
