### ISSUE TITLE
Suggest fish delivery + menu

### ISSUE THREAD

**Issue by ddman1211** [Oheers/EvenMoreFish#109]
add fish.yml 
and fish delivery.
fish artifacts to improve the quality of the rod.
a menu where all this can be edited.

**Comment by Oheers** [comment]
Fish.yml already exists, it should be in your /EvenMoreFish/ directory.
I do intend to add in a menu for accessing plugin features - though fish delivery is a cool idea, I've written your ideas on the todo list. Thank you :)

**Comment by sarhatabaot** [comment]
Fish delivery (directly to inv) was added in #398 
Menu have been added as well :)
