### ISSUE TITLE
Shift+click sell not counting

### ISSUE THREAD

**Issue by FinnChildress** [Oheers/EvenMoreFish#11]
If a fish is added into the "Sell Fish" menu via a SHIFT+CLICK after the "SELL" button is click (but before fully confirming) it will not be counted in the total money earned from the sale.

**Steps to recreate:**
1. Put a fish in the Sell Fish menu
2. Click the "Sell" button _once_
3. SHIFT+CLICK another fish into the menu
4. Click the confirm button

**Comment by FinnChildress** [comment]
When is the update containing this bug fix planned to release @Oheers?

**Comment by Oheers** [comment]
The release is set for tomorrow, apologies for not being very transparent about that.
