### ISSUE TITLE
no-winners, no-records when event ends

### ISSUE THREAD

**Issue by DexterSK** [Oheers/EvenMoreFish#116]
When i start contest by for example **/emf admin competition start 120**, then catching some fishes and contest is over it prints these values of

**contest-end**
**no-winners**
**no-record**

so its looks like i didn't have catched any fish

yes, i have data folder and .json there with UUID and values like

`[
  {
    "r": "Common",
    "n": "Fishing Rod",
    "c": 2,
    "t": 1648055218,
    "l": 13.8
  },
  {
    "r": "Common",
    "n": "Carp",
    "c": 4,
    "t": 1648055233,
    "l": 28.9
  },
.. etc
`

using last build even-more-fish-1.5.0.21.jar  from https://ci.codemc.io/job/Oheers/job/EvenMoreFish/
on purpur 1.18.2

**Comment by Oheers** [comment]
Hi there, I accidentally forgot to re-comment a section of the competitions.yml file that limits part of the plugin and seemingly creates a bug: by commenting the "required-worlds" setting in the general section, the problem will be fixed.

Also a new dev build was released which removes the debug messages, they were put in to diagnose an issue with the database which I believe is now partly fixed. :)

**Comment by DexterSK** [comment]
still same issue

**Comment by Oheers** [comment]
From what I've tested, removing required-worlds from the competitions.yml file and then doing `/emf admin reload` fixed the issue. Could you send your competitions.yml file please?

**Comment by DexterSK** [comment]
yep, missed that, fixed, thank you very much <3
