### ISSUE TITLE
MySQL prefix table names

### ISSUE THREAD

**Issue by TomLewis** [Oheers/EvenMoreFish#118]
You should prefix (And also let us set the prefix name in a config) of table names in MySQL, naming a table "users" is so vauge, this can easily conflict with many, many plugins that also don't prefix their tables. I suggest the default:
`emf_users`  and `emf_fish` It should also not be called `Fish2`.

**Comment by Oheers** [comment]
Ah thank you very much - I don't often work with databases so didn't realize that would be an issue. Thanks for letting me know :) I'll add it on the todo list.

**Comment by TomLewis** [comment]
No worries, I have a good 20+ years with them if you have any questions. 
Thank you for taking this suggestion on board.

**Comment by Oheers** [comment]
This has now been integrated as part of the database rewrite in an earlier commit.
