### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ProfessorDeBroglie** [Oheers/EvenMoreFish#131]
Server: 1.18.2
Plugin: latest

29.05 22:48:57 [Server] INFO DeBroglie issued server command: /emf admin competition start 10
29.05 22:48:57 [Server] ERROR null
29.05 22:48:57 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'emf' in plugin EvenMoreFish v1.5.0.29
29.05 22:48:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
29.05 22:48:57 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
29.05 22:48:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-345]
29.05 22:48:57 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]
29.05 22:48:57 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]
29.05 22:48:57 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
29.05 22:48:57 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
29.05 22:48:57 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
29.05 22:48:57 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
29.05 22:48:57 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-345]
29.05 22:48:57 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
29.05 22:48:57 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
29.05 22:48:57 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-345]
29.05 22:48:57 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-345]
29.05 22:48:57 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
29.05 22:48:57 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-345]
29.05 22:48:57 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-345]
29.05 22:48:59 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
29.05 22:48:59 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-345]
29.05 22:48:59 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-345]
29.05 22:48:59 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-345]
29.05 22:48:59 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
29.05 22:48:59 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by Oheers** [comment]
Is there possibly just a bit more underneath the "`29.05 22:48:59 [Server] INFO Caused by: java.lang.NullPointerException`"? It should contain "com.oheers." followed by the code location.

**Comment by ProfessorDeBroglie** [comment]
the error appears when using the pt_br translation.

if you want, i can translate and send pt_br for you

**Comment by Oheers** [comment]
That would be brilliant, the configs update quite a lot so I'm always really grateful to have them up-to-date. Thanks :)

**Comment by sarhatabaot** [comment]
Closed for inactivity
