### ISSUE TITLE
Migrate command does not have any output.

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#145]
EMF dev 58
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/58/

When using ``/emf migrate``, nothing is outputted in-game or on console. Instead only the command help info is sent.

**Comment by CloudeLecaw** [comment]
I just was have to test this once,because i deleted my old data after. But i renember the same result when i tried the Migration from database v2 to v3.

Now i cant retest it anymore because now the new database is on v3.

**Comment by sarhatabaot** [comment]
Closed for inactivity.
