### ISSUE TITLE
Schedules broadcast on no competitions started doubles after reloading

### ISSUE THREAD

**Issue by CloudeLecaw** [Oheers/EvenMoreFish#15]
Seen since Version 1.1.3

_part of config.yml_
```
competitions:


  # When should competitions run?
  # It will use server's local timezone using a 24hour time format
  times:
    - "12:00" # midday
```
i had added 12:12 because i wanne test the competitions scheduler
5 player are needed in config, im alone so i should get a meassage it does not start.

- To reproduce simply set minimum-players to 2 or more (when your alone) set a time that might be in 2-3 minutes from actual time and reload the plugin by its command **_/emf admin reload_**. Now wait for the time to come.

_Result - you will see the competitions has not started meassage twice_
![Snag_b0a9921](https://user-images.githubusercontent.com/12080017/115955574-9f372200-a4f7-11eb-93ea-2f7ebb6e7d5e.png)

- now change to time to 2-3 minutes alter and reload aggain and wait aggain

_Result - you will see the competitions has not started meassage tree times_
![Snag_b0b3fb2](https://user-images.githubusercontent.com/12080017/115955587-b70ea600-a4f7-11eb-8acc-1586c6c3ecee.png)

and so on...

**Comment by Oheers** [comment]
Fixed in #20
