### ISSUE TITLE
Custom fish head64 isn't work

### ISSUE THREAD

**Issue by Sigifon** [Oheers/EvenMoreFish#152]
![image](https://user-images.githubusercontent.com/109901921/180644517-943b1fd3-1f51-4489-bcfa-ad383ad1e89b.png)
![image](https://user-images.githubusercontent.com/109901921/180644522-f99962ee-c4b8-458d-94a9-1ae379848d8e.png)

Hi!,i play your amazing plugin,it very fun,but i cant see my head-64 work,it still steve head ,can you teach me how to fix the bug??
thanks

**Comment by Oheers** [comment]
Hey there, to use head-64 it needs to be inside an item: setting. Like so:
```
Sea Bass:
  displayname: "&ehead64"
  item:
    head-64: "eyJ0Z ..."
Cod2:
  item:
    head64: "eyJ0Z ..."
```

There's more info available on the [fish.yml wiki](https://github.com/Oheers/EvenMoreFish/wiki/Fish.ymll).
