### ISSUE TITLE
Compatible options

### ISSUE THREAD

**Issue by MineSunshineone** [Oheers/EvenMoreFish#158]
What should I set so that players can catch both the plugin's custom fish and the original loot?

**Comment by Oheers** [comment]
In your config.yml file, change `fish-only-in-competitions` from `false` to `true`. This means that when there's no competition going on, people won't be able to catch EMF fish and will instead catch just regular fish. It's also possible to give regular items by using a fish setup similar to the following:
```yml
Emerald Fish:
  item:
    raw-material: EMERALD
```

Hope this helps :)

**Comment by MineSunshineone** [comment]
I don't know where to add it below, is that right?
Emerald Fish:
  item:
    raw-material: EMERALD
fish:
  # ▼ All rarity names should start on the same column as this down arrow.
  #   ▼ All fish names should start on the same column as this down arrow.
  Common:

**Comment by Oheers** [comment]
(Apologies for the delayed reply)
Ooh no, it needs to be on the same line as all your other fish names, in whichever rarity you'd like it to be in.

**Comment by sarhatabaot** [comment]
Closed for inactivity.
