### ISSUE TITLE
Alert outputs display 0 seconds in time_formatted message.

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#163]
EvenMoreFish dev 138
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/

Is there any way to not display 0s in alert outputs?

```
# Sent to all players at specific times to show the remaining time left
# {time_formatted} shows the time (e.g. 5m left, 10m 30s left)
# {time_raw} is what you input in competitions.yml
time-alert: "&rThere is {time_formatted} left on the competition for {type}"
```

![link](https://i.imgur.com/gpOgQy4.png)
![link](https://i.imgur.com/uKbTfUp.png)

```
    alerts:
      - "5:00"
      - "1:00"
```

**Comment by Oheers** [comment]
Thank you ever so much for your patience, I somehow missed this.

Right now this isn't possible to get rid of it, but I'll put it on the todo list to be added to the plugin in the future.

**Comment by sarhatabaot** [comment]
This was actually implemented some time ago, but this issue was never closed. Enjoy!
