### ISSUE TITLE
Shift clicking in /emf shop

### ISSUE THREAD

**Issue by smuddgge** [Oheers/EvenMoreFish#165]
# Version
```
EvenMoreFish by Oheers 1.6.5
MCV: git-Purpur-1845 (MC: 1.19.2)
SSV: 1.19.2-R0.1-SNAPSHOT
Online: false
Loaded: Rarities(6) Fish(79) Baits(5) Competitions(168)
Database Engine: V3
```

# How to recreate

- `/emf shop`
- Shift click the `Sell all` option
- Exit the inventory

The item will still be in your inventory.
<img width="519" alt="Screenshot 2022-12-01 at 18 56 24" src="https://user-images.githubusercontent.com/68658429/205137423-cf8d70d7-8e9b-4760-9ef3-6fb073284a6d.png">

**Comment by Oheers** [comment]
This appears to just be a visual bug - albeit a very strange one. I've been able to reproduce this myself and it doesn't seem like I can do anything with the item such as place it or put it in a chest, similar to when you take an item out of a GUI with a poor internet connection.

But yeah, very strange but won't cause your tropical fish in a bucket server economy to crash 😜
