### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by jere62smi** [Oheers/EvenMoreFish#174]
Hello,
I allow myself to open this ticket because I encounter an error that I cannot understand.
I use version 1.6.4 of the plugin as well as version Purpur-1857.

![image](https://user-images.githubusercontent.com/31114661/208747173-ea9b8239-5736-43b6-8c2d-3c36fce90dcf.png)

**Comment by sarhatabaot** [comment]
Closed for inactivity. If you're still experiencing this issue with the latest version, please open a new ticket.
