### ISSUE TITLE
Placeholders do not display in holograms.

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#177]
EMF dev 152
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/152/
PlaceholderAPI dev 160
https://ci.extendedclip.com/job/PlaceholderAPI/160/
HolographicDisplays dev 243
https://ci.codemc.io/view/All/job/filoghost/job/HolographicDisplays/243/
Purpur dev 1882 (Paper 1.19.3)
https://purpurmc.org/downloads

EvenMoreFish placeholders do not seem to display in holograms.

![link](https://i.imgur.com/9gNlafC.png)

Testing that the placeholder works with ``/papi parse <name> <placeholder>`` does return it properly.

I tried different formats in HolographicDisplays to see if it was a formatting issue with no luck.
```
fishingevent:
  lines:
  - '&f&l{emf_competition_time_left}'
  - '&f&l%emf_competition_time_left%'
  - '&f&l%{emf_competition_time_left}%'
  - '&f&l{%emf_competition_time_left%}'
  ```
  
PlaceholderAPI _is_ enabled in HolographicDisplays config.yml and other plugin placeholders seem to display fine.
```
placeholders:
  PlaceholderAPI:
    enabled: true
    default-refresh-interval-ticks: 200
```

For example this placeholder from another plugin displays.
![link](https://i.imgur.com/QfceH13.png)

**Comment by Oheers** [comment]
Really sorry for missing this, would you mind trying in the latest version to see if this is still an issue?
