### ISSUE TITLE
How to get name special fish in fishing event

### ISSUE THREAD

**Issue by nogaruki** [Oheers/EvenMoreFish#178]
Hello I try to get fish by event : PlayerFishEvent
But I don't know how to convert the entiy get by the player to a instance of Fish from EventMoreFish.
Is there an API?

**Comment by Oheers** [comment]
Apologies for missing this, there is an API for the plugin and the maven information can be found here:
```xml
<dependency>
    <groupId>com.oheers.evenmorefish</groupId>
    <artifactId>even-more-fish</artifactId>
    <version>1.6.8</version>
</dependency>
``` 
then you'll want to use the `EMFFishEvent` instead in place of your PlayerFishEvent, and the #getFish() method from that.
