### ISSUE TITLE
Questions about fishing skills with Aurelium Skills

### ISSUE THREAD

**Issue by wlm1455925277** [Oheers/EvenMoreFish#192]
https://mclo.gs/J08Oc7Z
The Aurelium Skills fishing skill changes the item being fished for, and when the Aurelium Skills fishing skill item is caught with the fishing rod, the console will report an error!

**Comment by Oheers** [comment]
It may be something to do with the very first line - try adding in some `allowed-rarities` to your mainCompetition competition ^

**Comment by sarhatabaot** [comment]
Is this still an issue?

**Comment by sarhatabaot** [comment]
Closed for inactivity... If this is still an issue open a new ticket.
