### ISSUE TITLE
If you use 1.6.11 or higher, Japanese characters will be garbled.

### ISSUE THREAD

**Issue by sorandno** [Oheers/EvenMoreFish#208]
If you use 1.6.11 or higher, Japanese characters will be garbled.
Please respond properly.

**Comment by sorandno** [comment]
The reason is that it is converted to SHIFT-JIS even though it is saved in UTF-8.

**Comment by Oheers** [comment]
Looking into this right now, thanks for the report.

**Comment by sarhatabaot** [comment]
Fixed in latest version.
