### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by iLemon** [Oheers/EvenMoreFish#213]
I'd like to suggest support for Folia (https://github.com/PaperMC/Folia) to EvenMoreFish now that many public plugins are adding support.

This may be of interest: https://github.com/TechnicallyCoded/FoliaLib

**Comment by mbax** [comment]
As this plugin does not have the folia support flag in plugin.yml, that is in fact *not* the exception you would get when trying to load it on Folia.

**Comment by iLemon** [comment]
Removed the unneeded stacktrace, thanks @mbax

**Comment by FireML** [comment]
I opened a pull request here: #253 
Hopefully I didn't miss anything 🤞

**Comment by sarhatabaot** [comment]
Implemented via #253
