### ISSUE TITLE
Bug on end a competition

### ISSUE THREAD

**Issue by Xitryne** [Oheers/EvenMoreFish#217]
Stack:
org.bukkit.configuration.MemorySection.get(MemorySection.java:237)
org.bukkit.configuration.MemorySection.getDefault(MemorySection.java:863)
org.bukkit.configuration.MemorySection.getBoolean(MemorySection.java:370)
even-more-fish-1.6.11.3.jar//com.oheers.fish.config.MainConfig.databaseEnabled(MainConfig.java:45)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.handleRewards(Competition.java:698)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.end(Competition.java:111)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.processCompetitionSecond(Competition.java:154)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.decreaseTime(Competition.java:208)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.access$000(Competition.java:28)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition$2.run(Competition.java:135)
org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483)
net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397)
net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174)
net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
net.minecraft.server.MinecraftServer$$Lambda$4528/0x000000080153a808.run(Unknown Source)
java.base@18.0.2.1/java.lang.Thread.run(Thread.java:833)

**Comment by Xitryne** [comment]
ERROR15:10:15
net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483)
net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397)
net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174)
net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
net.minecraft.server.MinecraftServer$$Lambda$4528/0x000000080153a808.run(Unknown Source)
java.base@18.0.2.1/java.lang.Thread.run(Thread.java:833)
------------------------------
--- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
------------------------------
15:10:20
--- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-550 (MC: 1.19.4) ---
The server has not responded for 20 seconds! Creating thread dump
------------------------------
Server thread dump (Look for plugins here before reporting to Paper!):
------------------------------
Current Thread: Server thread
PID: 25 | Suspended: false | Native: false | State: RUNNABLE
Stack:
org.bukkit.configuration.MemorySection.get(MemorySection.java:255)
org.bukkit.configuration.MemorySection.getBoolean(MemorySection.java:376)
org.bukkit.configuration.MemorySection.getBoolean(MemorySection.java:371)
even-more-fish-1.6.11.3.jar//com.oheers.fish.config.MainConfig.databaseEnabled(MainConfig.java:45)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.handleRewards(Competition.java:698)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.end(Competition.java:111)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.processCompetitionSecond(Competition.java:154)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.decreaseTime(Competition.java:208)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition.access$000(Competition.java:28)
even-more-fish-1.6.11.3.jar//com.oheers.fish.competition.Competition$2.run(Competition.java:135)
org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483)
net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397)
net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174)
net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
net.minecraft.server.MinecraftServer$$Lambda$4528/0x000000080153a808.run(Unknown Source)
java.base@18.0.2.1/java.lang.Thread.run(Thread.java:833)

**Comment by Oheers** [comment]
Hi there I've had a few reports, there'll be a spigot release with this fix clearly stated in the changelog once I've managed to implement a fix. Thank you for your report :)

**Comment by Xitryne** [comment]
Hi, thanks you very much !

**Comment by Xitryne** [comment]
When is the update coming?

**Comment by SMHenrry** [comment]
This bug is still present in the latest version (1.6.11.15)

**Comment by madebygood** [comment]
I haven't been able to use evenmorefish on my server for nearly two months.

My heart aches.

**Comment by sarhatabaot** [comment]
> I haven't been able to use evenmorefish on my server for nearly two months.
> 
> My heart aches.

Can you try using this version & lmk if the issue is still present? https://github.com/Lapzupi/EvenMoreFish/releases/tag/database-issue-2

**Comment by madebygood** [comment]
> > I haven't been able to use evenmorefish on my server for nearly two months.
> > My heart aches.
> 
> Can you try using this version & lmk if the issue is still present? https://github.com/Lapzupi/EvenMoreFish/releases/tag/database-issue-2

This PR is resolve with this problem?
https://github.com/Oheers/EvenMoreFish/issues/182

If true, I will retest!

**Comment by sarhatabaot** [comment]
> > > I haven't been able to use evenmorefish on my server for nearly two months.
> > > My heart aches.
> > 
> > Can you try using this version & lmk if the issue is still present? https://github.com/Lapzupi/EvenMoreFish/releases/tag/database-issue-2
> 
> This PR is resolve with this problem?
> https://github.com/Oheers/EvenMoreFish/issues/182
> 
> If true, I will retest!
> 

Yes, possibly. I don't experience this issue so it would be great if someone else could test it as well.

**Comment by madebygood** [comment]
> > > > I haven't been able to use evenmorefish on my server for nearly two months.
> > > > My heart aches.
> > > 
> > > 
> > > Can you try using this version & lmk if the issue is still present? https://github.com/Lapzupi/EvenMoreFish/releases/tag/database-issue-2
> > 
> > 
> > This PR is resolve with this problem?
> > #182
> > If true, I will retest!
> 
> Yes, possibly. I don't experience this issue so it would be great if someone else could test it as well.


Same issue.
