### ISSUE TITLE
1.20.1 - Could not pass event PlayerFishEvent to EvenMoreFish v1.6.11.13

### ISSUE THREAD

**Issue by shortybsd** [Oheers/EvenMoreFish#219]
I have tournaments setup every hour, the first one works fine then after I get errors thrown on server and tournament never starts. I have to manually end the tournament and start back up for it to work. It did this with release version (1.6.11.3) as well.

EvenMoreFish Version: 1.6.11.13 & 1.6.11.3
Server: Purpur Version: 1.20.1-2019
Pastebin - https://pastebin.com/Rbn8e5Sx

**Comment by sarhatabaot** [comment]
This has been fixed in one of the newer versions.
