### ISSUE TITLE
Plugin using built-in dependency over newer given dependency

### ISSUE THREAD

**Issue by ryzech** [Oheers/EvenMoreFish#235]
On 1.20.2 EvenMoreFish seems to be ising NBT-API version 11.3.0 over 12.0. This is an issue because 11.3.0 doesn’t support 1.20.2.

Im unsure as to why its using a built in dependency in the first place, but regardless it needs to be updated in order to fully work on 1.20.2

**Comment by sarhatabaot** [comment]
EMF is using NBTAPI 2.12.0, not sure where you're getting that other version from, this was fixed in one of the latest PRS.
To get the newest version of emf you can build the file yourself or wait for the next dev build.
