### ISSUE TITLE
paper 1.20.2 err

### ISSUE THREAD

**Issue by With-for** [Oheers/EvenMoreFish#240]
![image](https://github.com/Oheers/EvenMoreFish/assets/149612752/6aad72b2-a44c-4f5d-9698-c58a7d4e2e38)
![image](https://github.com/Oheers/EvenMoreFish/assets/149612752/6ed43259-6bbb-4909-b5ba-4161a8e2267d)

In some cases, vanilla items are given because lore or name does not apply well.

and bait too err

**Comment by With-for** [comment]
![image](https://github.com/Oheers/EvenMoreFish/assets/149612752/aa1fa38a-3469-46ab-b2db-1347eb79a554)

**Comment by sarhatabaot** [comment]
Is there any error in the console when this happens?

**Comment by With-for** [comment]
It doesn't appear on the console. 
Check through Discord Forum to reflect the opinions of other users and use the default value, the same error will occur.

**Comment by javieralvarezlo** [comment]
Any fix on this? Facing the same issue

**Comment by sarhatabaot** [comment]
Is this issue still present in latest dev builds?
