### ISSUE TITLE
feature request: /emf sellall

### ISSUE THREAD

**Issue by NotAShelf** [Oheers/EvenMoreFish#241]
Basically a `/emf sellall` command that provides the functionality of the "sell all" button on the gui - this should be easy to implement, but I couldn't figure out how to. Someone more experienced with the codebase and java might be able to.

**Comment by FireML** [comment]
I opened a pull request to add it here: #252

A sellall command would be very helpful

**Comment by NotAShelf** [comment]
Looks good, I'll test it when I get the chance.

**Comment by sarhatabaot** [comment]
Implemented via #252
