### ISSUE TITLE
Incorrect message at the end of the competition

### ISSUE THREAD

**Issue by Sombeyyy** [Oheers/EvenMoreFish#244]
Problem:
At the end of the competition, a leaderboard will be issued for each player. However, the message that no competition is currently running is displayed instead.

Solution:
This is because the variable "active" is set to false in the **end() method** of the **Competition class**. Further down in the method, the method sendPlayerLeaderBoard() is called for each player. This checks whether a competition is currently running. As the variable has already been set to false, no leaderboard is output.
The variable should be changed after the call.

**Comment by Sombeyyy** [comment]
I have already tried to open a PullRequest that solves the problem, but I do not have permission to do so.

**Comment by sarhatabaot** [comment]
> I have already tried to open a PullRequest that solves the problem, but I do not have permission to do so.

To open a PR, create a fork of the repo, then submit a PR via that fork. 
I can review and merge the PR.

**Comment by Sombeyyy** [comment]
Oh sorry, my mistake. I have opened the PullRequests (#246 )

**Comment by sarhatabaot** [comment]
Fixed via #246
