### ISSUE TITLE
[ERROR] 1.20.2 - CustomModelData isn't working!

### ISSUE THREAD

**Issue by sharkaholic** [Oheers/EvenMoreFish#249]
Hey there,

After updating to 1.20.2, it seems that the CustomModelData line no loner functions. The chat announcement works, as does the actionbar pop-up, but all we receive is sticks! 👍 

Could this please be resolved? We miss our custom fishies!

**Comment by FireML** [comment]
This seems to have been fixed with what i did here #251 
It should be in the next Spigot release.

**Comment by sarhatabaot** [comment]
Fixed by #251
