### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by Oheers** [Oheers/EvenMoreFish#25]
Placeholders for:

current competition winners, (1st,2nd,3rd,ect)
total competition winners (most wins, biggest fish, ect)
time until next competition
placeholders for every rarfity

**Comment by exzolink** [comment]
Hi! Would be great if you add total caught placeholders for every rarity.
Thanks :)

%evenmorefish_total_<rarity>% for example

**Comment by Oheers** [comment]
Moved to Asana.
