### ISSUE TITLE
Server crashes when running a fish event

### ISSUE THREAD

**Issue by MasterGabeMOD** [Oheers/EvenMoreFish#255]
Here's the error log: https://pastebin.com/BBLrTdVg

Config.yml: https://pastebin.com/yLxT1eHL

Fish.yml: https://pastebin.com/Sgu4L5mn

Baits.yml: https://pastebin.com/vvLnJg9g

Competitions.yml: https://pastebin.com/FWtVWbg6

The rest of the configs are defaults. 

We were initially running version 1.6.11.16 from Spigot, but I compiled the latest 1.6.11.17 from here on Github to see if that would resolve it. Unfortunately, the same crash error persists. We're running Purpur 1.20.2. 

Edit: Just to note on this, the crash occurs after the event ends.

**Comment by MasterGabeMOD** [comment]
> How many people are in the competition when this happens? Any chance you can send me your full log (in a DM on discord - sarhatabaot).

Sorry for the late response. The issue occurred in a testing environment with only myself and three other people. The server crash occurs when manually initiating an event, while scheduled events did not lead to any problems.

**Comment by MasterGabeMOD** [comment]
Here's a couple more errors that occurred on the latest version.

1) https://pastebin.com/WvKfptxR

2) https://pastebin.com/nSbVtaK1

The only issue is it hasn't generated a crash report log into the crash-reports folder. This is the most detailed information that I have at the moment.

**Comment by sarhatabaot** [comment]
Can you try running the latest dev build and let us know if the issue persists? 
There have been a lot of changes since January.
