### ISSUE TITLE
Error console + Competitions are not starting

### ISSUE THREAD

**Issue by DiktatorAladeen** [Oheers/EvenMoreFish#258]
Hi,

I setup competitions 3 times per day but it is not starting, when i want to start competition manually it is showing error ...
![image](https://github.com/Oheers/EvenMoreFish/assets/34982264/0ff42577-be22-4304-8f67-f9c5af8c85bf)

This error is spamming in console:
https://pastebin.com/QJ4R00C4

**Comment by sarhatabaot** [comment]
Can you rename your messages file to messages.old.yml and let it regenerate?

**Comment by sarhatabaot** [comment]
Closed for inactivity.
