### ISSUE TITLE
NBT data is not applied to items unless they are Salmon or Cod.

### ISSUE THREAD

**Issue by xenxero1** [Oheers/EvenMoreFish#266]
Using the latest release of EMF from 2022, on a paper server for 1.20.4 I get this message on server startup.

[03.01 10:26:45] [Server] [WARN] [NBTAPI] [NBTAPI] This Server-Version(v1_20_R3) is not supported by this NBT-API Version(2.12.0) located in EvenMoreFish. The NBT-API will try to work as good as it can! Some functions may not work!

Whenever one of my players fishes up an item that is not salmon or cod, it defaults back to giving them the item with no NBT data, including nether stars. This issue is also causing items to not receive the designated renames or EMF length/shop values, their noCrafting nbt tag, or even durability modifiers for things like fishing rods.

**Comment by sarhatabaot** [comment]
Closed as it's fixed in dev versions. Unofficial dev version are available here: https://ci.firedev.uk/job/EvenMoreFish/
