### ISSUE TITLE
Addon Request: GUI for adding custom items

### ISSUE THREAD

**Issue by xenxero1** [Oheers/EvenMoreFish#267]
I want to be able to add customized items that use modified attributes and customized enchantments to my fishing loot tables, to make fishing a necessary part of building up to my servers pvp endgame. Currently, the only method I have to add items to the fishing loot pool is to text edit the fish.yml file, which makes adding certain specific NBT data incredibly difficult, and in some cases impossible.

I think being able to add in items via GUI would make this process a lot smoother since there are other ways to create the item in-game which could then be imported. Beyond my use case, it also allows EMF to have greater flexibility for user-side management.

**Comment by FireML** [comment]
The linked pull request isn't a GUI, but it will allow you to do what you want.
