### ISSUE TITLE
Fish points and infinite baits with commands

### ISSUE THREAD

**Issue by Hidius** [Oheers/EvenMoreFish#271]
Hello, first of all I send you my greetings. I want to say that this is one of the most incredible plugins that I have been able to add to my server and I would really like to leave some suggestions and we as a community would greatly appreciate it. It would be incredible if they could link the PlayerPoints plugin with their plugin to be able to sell for money and at the same time for points. I saw this idea on a server and I think it would be cool. It would be good if 2 economies could be added at the same time, that is, you could sell a certain value to Vault and a lower value to PlayerPoints as if it were a points system that is difficult to obtain. Another suggestion would be to be able to obtain rods with infinite baits directly from the commands, that is, for example you can obtain a rod capable of fishing for legendary fish x2 times faster. Thank you very much for this incredible plugin.
![zN9IVlY](https://github.com/Oheers/EvenMoreFish/assets/130802937/6a9705db-9316-46b3-858d-ebec6d28dc6a)

**Comment by noaskers** [comment]
This is a very cool idea. As far as I know, Oheers is really busy right now, so I don't think this will be added very quickly.

**Comment by sarhatabaot** [comment]
I realize now that this isn't fully implemented, or we just didn't understand the request. Reopening for now.
