### ISSUE TITLE
CoinsEngine Support

### ISSUE THREAD

**Issue by FireML** [Oheers/EvenMoreFish#286]
If possible would be cool to add support for this one aswell:
https://www.spigotmc.org/resources/coinsengine-economy-and-virtual-currencies.84121/

And it would also be cool if we can give these after selling fish at the shop ;)

_Originally posted by @noaskers in https://github.com/Oheers/EvenMoreFish/issues/273#issuecomment-1934516517_

**Comment by FireML** [comment]
The dev of CoinsEngine will need to provide a better way of accessing the plugin's API before this is possible. If we get a better way, i can do this.

**Comment by noaskers** [comment]
Is this one possible to add support for?

https://www.spigotmc.org/resources/%E2%9C%AA-coinsapi-1-8-1-20-vault-placeholderapi-%E2%9C%AA.35150/

**Comment by FireML** [comment]
> Is this one possible to add support for?
> 
> https://www.spigotmc.org/resources/%E2%9C%AA-coinsapi-1-8-1-20-vault-placeholderapi-%E2%9C%AA.35150/

this one looks to have the same issue

**Comment by noaskers** [comment]
And this one:

https://www.spigotmc.org/resources/gemapi-for-elementalgems.97313/

Is this a good enough API

**Comment by noaskers** [comment]
What is the problem with them all like they even have an open API :/

**Comment by FireML** [comment]
> What is the problem with them all like they even have an open API :/

They all require you to use the jar file itself instead of having a maven repository to use

**Comment by noaskers** [comment]
sorry, but no way currently for that. i dont see any issues when installing it to local repo from .jar


Response from coinengine dev ^

**Comment by FireML** [comment]
@sarhatabaot mentioned it in another request: https://github.com/nulli0n/CoinsEngine-spigot/issues/17

**Comment by noaskers** [comment]
So with the response of that dev would it still be possible to add it cus the problem is i already use playerpoints for my paid server currency and would really much like to have it added or any other option

**Comment by FireML** [comment]
Unfortunately not, sorry

**Comment by FireML** [comment]
Closed due to the dev not wanting to provide a maven repo for the API
