### ISSUE TITLE
[Suggestion] Placeholder additions

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [Oheers/EvenMoreFish#287]
Hello,

I'd love to get those two placeholders added, as they would give a lot of nice information:
• When the next competition is (Dayname, the dd,mm,yyyy at hh:mm) (even better let us chose an own format and language for it!:)
• The time left until the next competition.

Best regards!:)

**Comment by sarhatabaot** [comment]
Great idea!

**Comment by ILikeOrangeJuice** [comment]
Apparently there is %emf_competition_time_left% which I found randomly in the messages.yml which appeared after I recreated the file as it doesn't auto update haha, there u can define all of those things, so I close this :).
