### ISSUE TITLE
Improve Command System

### ISSUE THREAD

**Issue by sarhatabaot** [Oheers/EvenMoreFish#316]
Currently the command system we use is very messy. Adding a command requires us to add logic to a long switch method & also update tab completion methods.
We should do 2 things:
- Move to a command framework [ACF](https://github.com/aikar/commands) 
- Move logic of every sub command to it's own class -  for better readability.

I've previously worked with [ACF ](https://github.com/aikar/commands)so that's what I'll work on with the PR for this feature.

**Comment by FireML** [comment]
Maybe also fix the custom competition command while doing this?
Here is the link to what I mean: https://discord.com/channels/831387950401978398/884501996546166845/1227336739295596564

**Comment by sarhatabaot** [comment]
Implemented via #317
