### ISSUE TITLE
Spam error of skull meta

### ISSUE THREAD

**Issue by SMarc1** [Oheers/EvenMoreFish#344]
[22:08:23 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).

Version server 1.20.4 pufferfish

**Comment by SMarc1** [comment]
Version plg 1.7

**Comment by FireML** [comment]
This is fixed in the latest dev build: https://ci.codemc.io/job/Oheers/job/EvenMoreFish/
