### ISSUE TITLE
Suggestion, /efm shop <playername> that has its own permission for NPCS.

### ISSUE THREAD

**Issue by TomLewis** [Oheers/EvenMoreFish#356]
I would like to have the emf shop open via an NPC, not anywhere from a command.
A quick way to do this, is to add /emf shop <playername> that has its own permission, so then we can deny use of this command and make the NPC run it with %playername% placeholder. 

Then they can only access it via the NPC and not command.

**Comment by sarhatabaot** [comment]
`/emf shop` already has it's own permission: `emf.shop`

**Comment by TomLewis** [comment]
Like the CMI sudo?

**Comment by sarhatabaot** [comment]
It should be ran as an admin automatically.
