### ISSUE TITLE
Error 1.20.6

### ISSUE THREAD

**Issue by VentureStudios** [Oheers/EvenMoreFish#359]
https://mclo.gs/OwhATrJ

**Comment by sarhatabaot** [comment]
You can safely ignore this for now. 
We're aware of this issue and are waiting for a fix from the developer of the commands api we are using.

**Comment by FireML** [comment]
There's an open issue for it on their GitHub page: https://github.com/aikar/commands/issues/409

**Comment by FireML** [comment]
Fixed in #486
