### ISSUE TITLE
[Bug]: Constanly overwriting files and ignora database

### ISSUE THREAD

**Issue by TheoMarque** [Oheers/EvenMoreFish#391]
### What happened?

I am tired to config this plugin. Constantly overwrite any config files if I do some mistake in yml syntax. just remove and parte default values - sending all work to space. Not fail and not run and stop but run with default config making all changes useles - not use fish shops and if configs reset to default players ask me how to sell fishes - but send whole economy into void. Why? because  parsing some part of messages was broken. 
Same situation with database - plugin has configured mysql connection but.. not create any tables. Just ignore it. User in DB can create tables but plugion not do it. 

I think its most stupid configuration system seen in any plugins - reset to default if something was wrong and not THROW any errors in console, just silently replace with default values - like xmas2022.yml - I removed it but back every server restart. 

### Version

1.7 (latest)

### Development Version

1.7.2

### Server Version

latest 1.21 paper

### Java Version

21

### Relevant log output

```shell
Logs that contains wrong values but NOT point WHAT values are wrong and reset to default.
```

**Comment by sarhatabaot** [comment]
Couple of things here,
I understand your frustrations but actually almost all plugins have default values for config settings. This is to prevent issues if the setting does not exist for some reason in your file (i.e. added at a later version or hidden for some reason).

As for the database, I'm not sure what you mean? It works for us and the rest of the users, please be more descriptive, did you change the setting, and then restart the server?
What mysql version are you running? Are there any errors in the console regarding the database?

**Comment by TheoMarque** [comment]
Overwrite config by default cause plugin unusable due demolishing other settings - for example rewards or enable shops. Not support any shops and if shops are enabled - spam into logs with ton of errors. Even we not have Vault. 
I prefer not run plugin than overwrite config. Similar situation is with messages.yml - overwrite with default, even I translate whole file, just typo and need to copy and paste whole texts making more typos. Removing permissions to overwrite cause spam in console permission denied. Best practice - create temp directory (if needed, but most default configs run just from .jar file in memory) files are needed to run and info admin that run at default config not overwrite them!

Database problem, enables but not touch database, just ignored it. Not incoming connections nad not in console any info about it. Like just whole part of db not implemented.

**Comment by sarhatabaot** [comment]
Can you please use the latest dev version, and let us know if there are still issues with database?

Let's approach the issues one by one or else this will never end.

A note about database, for it to work, you should restart the server.
So stop the server, change the settings, then start it again.

Just in case, rename your config.yml file to config.yml.old, let a new one generate, and then compare the values to see if anything is missing. 

Also, if you could send me in a dm your setup that would make it easier for us.
Discord username: sarhatabaot

**Comment by sarhatabaot** [comment]
I will split this issue into 2 or 3 issues soon.

**Comment by sarhatabaot** [comment]
Default by default only overwrites settings if they are missing, if values are present they do not get overwritten.

If you want to disable a setting you must set it to false or what ever value is relevant.

**Comment by sarhatabaot** [comment]
The config system has been changed to make more sense! Still unsure what your issues with database are. Please open a new issue for those.
