### ISSUE TITLE
[Suggestion (Plugin)]: messages_fr.yml : French mistake

### ISSUE THREAD

**Issue by WenGeb** [Oheers/EvenMoreFish#421]
### First of all, sorry for my english x)

![Capture d'écran 2024-08-28 023536](https://github.com/user-attachments/assets/39d0b8d1-7ade-4099-8101-00c5c939e457)

The first message is not correct, in French you should say the **size after saying the name of the fish**.
I also recommend changing **"un"** to **"un(e)"** if users want to add fish with **a feminine noun**.

### So the correct 4 first ligns are :
```
# Envoyé aux joueurs quand ils pêchent un poisson EvenMoreFish
fish-caught: '&l{player} &ra pêché un(e) {rarity_colour}&l{rarity} {rarity_colour}{fish} de {length}cm !'
# En définissant la longueur minimale d'un poisson à moins de 0, vous pouvez créer un poisson sans longueur.
lengthless-fish-caught: '&l{player} &ra pêché un(e) {rarity_colour}&l{rarity} {rarity_colour}{fish}!'
```

**Comment by FireML** [comment]
thank you, i'll open a pr to fix that now :slightly_smiling_face:
