### ISSUE TITLE
[Suggestion (Plugin)]: Competition Refactor

### ISSUE THREAD

**Issue by sarhatabaot** [Oheers/EvenMoreFish#443]
### Suggestion

We should refactor the Competition class file.
It does too many things at once. Each competition type should be implemented in a different class file.
I don't really have time to implement this so leaving this issue open so we don't forget.

**Comment by FireML** [comment]
My suggestions:
- Split the Leaderboard class between each competition type
- Move the applyToLeaderboard method to the Leaderboard class
- Move the sendPlayerLeaderboard method to the Leaderboard class (and sendConsoleLeaderboard, but these should probably be merged for cleanliness)
- Add a getChatMessage to the Leaderboard class, which is used by the sendPlayerLeaderboard and can be used elsewhere if needed

**Comment by FireML** [comment]
Plan:
- Turn CompetitionType into an interface
- Add all type-specific code to each type's implementation of that interface
- Remove the Leaderboard class
- Have each CompetitionType provide its own instance of LeaderboardHandler
- Add CompetitionManager to handle all competition-related things
- Allow custom CompetitionTypes to be registered by third party plugins

**Comment by sarhatabaot** [comment]
Implemented in #494 & #459
