### ISSUE TITLE
fish.yml, rarities.yml keeps getting reset.

### ISSUE THREAD

**Issue by minejango2** [Oheers/EvenMoreFish#508]
### Contact Details

minejango2@gmail.com

### What happened?

I don't know why, but when I import the fish.yml and rarities.yml files that I used in EvenMoreFish 1.7.3 version into 2.0.0#163 (1.7.4), both files return to the way they were when I first installed the plugin.

I did it when I turned on the server.

rarities.yml:
https://pastebin.com/NNMqbsSE

fish.yml:
https://pastebin.com/qjthXVmc

### Version

1.7.4

### Development Version

2.0.0#163

### Server Version

Paper 1.21.3-81-master@da71382 (MC: 1.21.3)

### Java Version

21

**Comment by FireML** [comment]
i am seeing the issue with rarities, but not fish. could you check the fish.yml file again?

**Comment by minejango2** [comment]
new fish.yml
https://pastebin.com/vrLadh9p


sorry for the confusion

**Comment by FireML** [comment]
Alright, that confirms my suspicions. I'll look into it.

**Comment by FireML** [comment]
My suspicions were wrong, but I am about to PR a fix for this issue.
