### ISSUE TITLE
Shop Bug

### ISSUE THREAD

**Issue by TechieCrow** [Oheers/EvenMoreFish#63]
Think I found a slight bug with the shop.

So when you place a fish in the shop GUI the price doesn't update unless you click on something else, for example placing 1 fish in the shop will still show $0.0 unless you click on a glass plane or place something else in the shop, then the price will update.

Also not sure if this is possible but having the GUI only accept EMF fish would be really nice but I guess isn't a big issue. :)

**Comment by Oheers** [comment]
Heya - thanks for the report, before the 1.0 release when adding in the shop I tried to have it as a "live" counter however it seemed I couldn't figure out how to change a GUI item without cancelling the event (you don't want to cancel a player putting an item into the inventory) but reading this has sparked an idea that might fix it, soI'll add this as a higher priority bug for now and get back to you once it's tweaked.

**Comment by Oheers** [comment]
I'm currently working on something completely unrelated but still with the plugin and I've noticed that the count has miraculously become a live counter now. I have no recollection of ever adding it in, but if it stays that way that's brilliant stuff haha.

**Comment by TechieCrow** [comment]
Haha love happy accidents, this is awesome thanks for keeping me up to date!
