### ISSUE TITLE
Issue where the leaderboard takes in latest value rather than top value

### ISSUE THREAD

**Issue by Oheers** [Oheers/EvenMoreFish#7]
Currently working on getting a fix onto the master branch.

**Comment by Oheers** [comment]
This was discovered with non-standard conditions, where legendaries were given a weight of 10,000 over all other weights being config.yml default. Resetting this to normal appears to have fixed the issue but a certain cause was never found, and it appeared to be spontaneously failing (Float > Float) checks in Competition.class line 66. 

If anybody else has more information on the matter, please leave a comment below and this will be an issue that remains open.

**Comment by PancakeCatsss** [comment]
Can confirm this is still an issue

**Comment by Oheers** [comment]
Thank you, I'll spend some time looking into this today.

**Comment by Oheers** [comment]
Cause: a player fishes a fish that gets set as their highest (e.g. golden axelotl), then a smaller version of that fish is fished, during the generateSize() call in Fish.java, this also affects the other larger golden axelotl that has been stored in the leaderboard register.
