### ISSUE TITLE
exiting /emf shop with escape leaves items from GUI in your equipment  

### ISSUE THREAD

**Issue by Bloodlex** [Oheers/EvenMoreFish#71]
Hello,

When exiting from /emf shop with escape, you take every icon that is there in GUI. Could you please help with that? 🙁 Thank you for your help.

**Comment by Oheers** [comment]
Sorry for the lack of response recently, I'm pushing a major update tomorrow (hopefully) and after that I'll try again to reproduce the error you're experiencing to have it fixed in the 1.4.1 release.

**Comment by Oheers** [comment]
I'm looking into this issue prior to the 1.4.1 release scheduled for tomorrow, however i'm struggling to reproduce the error you mentioned. It seems that the "commands: - emf shop" is just a way of getting to the shop but once I'm in the shop, pressing escape just closes the shop as normal: CommandPanel has finished all it needs to do. Here's my process, please let me know where I'm going wrong.

`panels:
  template:
    perm: admin
    rows: 1
    title: '&8Template Panel'
    empty: GLASS_PANE
    item:
      '4':
        material: COBBLESTONE
        stack: 1
        name: '&fClick Me!'
        commands:
        - emf shop`

- Running the command /cp template from my Minecraft window
- Clicking on the cobblestone -> /emf shop is opened
- Pressing ESC -> nothing is dropped nor added to my inventory, even in the presence of some fish in the shop.

**Comment by sarhatabaot** [comment]
Closed for inactivity, if this issue is still a problem, reopen the issue.
