### ISSUE TITLE
Competition ends right after start

### ISSUE THREAD

**Issue by Bloodlex** [Oheers/EvenMoreFish#75]
Hello,

I have a problem, because sometimes my competitions end right after start. Maybe it's something wrong with my config, but I can't see it, because I have set duration everywhere properly I suppose. Could you take a look on that and tell me if everything's okay?

My competition file: [https://pastebin.com/H718EJrJ](https://pastebin.com/H718EJrJ)

![image](https://user-images.githubusercontent.com/1086720/132660604-337d2e9a-1c25-4f03-99bc-c772675826d4.png)

It says a competition started, ended, you haven't catched any fish and there were no records and it happens immediately.

Thank you very much! 🙂

**Comment by Oheers** [comment]
This error was fixed in the latest patch, I'm happy to give it to you if you join the discord server and open a ticket - or if you don't have discord I'm happy to send it to you any other way of your choosing.

**Comment by Oheers** [comment]
I've posted a new update on Spigot which includes this patch.

**Comment by Bloodlex** [comment]
> I've posted a new update on Spigot which includes this patch.

Thank you so much! Amazing plugin by the way and excellent support 🙂 👍
