### ISSUE TITLE
Timer consistency

### ISSUE THREAD

**Issue by Xorgon** [Oheers/EvenMoreFish#78]
The [current tick-based timer](https://github.com/Oheers/EvenMoreFish/blob/master/main/java/com/oheers/fish/competition/Competition.java#L108) relies on accurate tick timing to achieve accurate event timing. This can lead to significantly longer competitions if the server isn't running at maximum ticks. Perhaps consider using server time to determine time remaining rather than how many ticks have passed.

**Comment by Oheers** [comment]
Thank you very much, I'll try implementing this some time tomorrow possibly, or at least before the next update.

**Comment by Oheers** [comment]
The timer now syncs with the real time at regular intervals to prevent this from ocurring. Thanks for reporting :)
