### ISSUE TITLE
The blacklisted-days setting not work in competitions.yml

### ISSUE THREAD

**Issue by andris155** [Oheers/EvenMoreFish#79]
The blacklisted-days setting not work in competitions.yml. The Competitions running in blacklisted days if I set it up.

**Comment by andris155** [comment]
EvenMoreFish version 1.4.0.5
Paper 1.17.1 build 263

**Comment by Oheers** [comment]
I'll check this out later today - thanks for reporting.

**Comment by ApolonArbre** [comment]
Hello, I have the same problem on my server, the event starts even on blacklisted days
EventMoreFish version 1.5.0.1
Java 16 Serveur in 1.17

**Comment by Oheers** [comment]
Apologies for the delayed reply @ApolonArbre I'll see if I can replicate this later today.
