### ISSUE TITLE
Cant load messages on fresh install

### ISSUE THREAD

**Issue by exzolink** [Oheers/EvenMoreFish#95]
Cant load messages.yml on fresh install

**Comment by Oheers** [comment]
Cheers, I've discovered this on my test server, I'll try and put together a fix asap.

**Comment by exzolink** [comment]
Can you also check getBlock#getBiome, it throws null every time i catch fish

**Comment by exzolink** [comment]
> Cheers, I've discovered this on my test server, I'll try and put together a fix asap.

Can you also check getBlock#getBiome, please, it throws null every time i catch fish

**Comment by Oheers** [comment]
I've got a fix for that already, I'm going to make a patch update either tonight or tomorrow night which should solve a lot of problems people have been having.

**Comment by Oheers** [comment]
Fixed in 1.4.2.3.
